apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtc-web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mtc-web
  template:
    metadata:
      labels:
        app: mtc-web
    spec:
      containers:
      - name: mtc-web
        image: mtc-web-nginx:v2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80