apiVersion: v1
kind: Pod
metadata:
  name: mtc-web1
  labels:
    app: mtc-web
spec:
  containers:
  - name: mtc-web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80